name: Preview Terraform Plan
 
on:
 
  pull_request:
 
jobs:
 
  preview:
 
    name: Plan
 
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Checkout
 
        uses: actions/checkout@v3
 
        with:
 
          ref: ${{ github.head_ref }}
 
          fetch-depth: 0
 
      - name: setup go
 
        uses: actions/setup-go@v3
 
        with:
 
          go-version: "1.20"
 
      - name: Terramate install
 
        run: go install github.com/terramate-io/terramate/cmd/...@latest
 
      - name: Terramate List changed stacks
 
        id: list
 
        run: |
 
          echo "results<<COUT" >>$GITHUB_OUTPUT
 
          terramate list --changed >>$GITHUB_OUTPUT
 
          echo "COUT" >>$GITHUB_OUTPUT
