name: Scan Terraform Modules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install Terramate
      run: |
        go install github.com/mineiros-io/terramate/cmd/terramate@latest

    - name: Scan Terraform modules
      run: |
        terramate fmt -recursive
        terramate validate -recursive
